# Generated by Django 5.1.7 on 2025-03-25 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HashCode', models.CharField(max_length=255)),
                ('FilePath', models.CharField(max_length=255)),
                ('IsDeleted', models.BooleanField(default=False)),
            ],
        ),
    ]
